### ISSUE TITLE
I have met this error when bundle install.

### ISSUE THREAD

**Issue by bemoregt** [PokeData/PokeGAN#1]
Hi, @adrianodennanni , @ThiagoLira 

I have met this error when bundle install.

oem@sgi:~/PokeGAN$ bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this
application for all non-root users on this machine.
Warning: the running version of Bundler (1.16.1) is older than the version that created the lockfile (1.16.6). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Fetching gem metadata from https://rubygems.org/.........
Using public_suffix 3.0.3
Using addressable 2.5.2
Using bundler 1.16.1
Fetching byebug 10.0.2
Installing byebug 10.0.2 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.5.0/gems/byebug-10.0.2/ext/byebug
/usr/bin/ruby2.5 -r ./siteconf20181031-7621-10j88wq.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.5.0/gems/byebug-10.0.2 for inspection.
Results logged to /var/lib/gems/2.5.0/extensions/x86_64-linux/2.5.0/byebug-10.0.2/gem_make.out

An error occurred while installing byebug (10.0.2), and Bundler cannot continue.
Make sure that `gem install byebug -v '10.0.2'` succeeds before bundling.

In Gemfile:
  byebug

What's wrong with me?

from @bemoregt.

**Comment by adrianodennanni** [comment]
Could you please inform which Ruby version are you using?

**Comment by adrianodennanni** [comment]
This seems to be an issue with your the Ruby installed in your machine. Did you install it using RVM? I recommend doing so.
If you don't want to use RVM, try installing ruby with `sudo apt-get install ruby2.5 ruby2.5-dev`, if you are using any Debian-like distro.

**Comment by adrianodennanni** [comment]
Since no feedback was given, I am closing this issue.
